"""add argument extraction AIF/IAT tables

Revision ID: 21357d22b7e3
Revises: 0020_edition_source_header
Create Date: 2026-01-24 16:09:59.729683

This migration adds AIF/IAT argument extraction tables:
- ArgumentExtractionRun: pipeline tracking
- ArgumentLocution: L-node (bridges Paragraph/SentenceSpan)
- ArgumentProposition: I-node (informational content)
- ArgumentIllocution: L→P edge (illocutionary force)
- ArgumentRelation: S-node (argumentative relations)
- ArgumentTransition: discourse markers
- EntityCatalog & EntityBinding: entity normalization

These are complementary to existing Claim/ConceptMention tables (Stage A/B),
not replacements. They serve the dialectical argument structure pipeline.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '21357d22b7e3'
down_revision = '0020_edition_source_header'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types for new argument extraction tables
    argumentrelationtype_enum = sa.Enum('support', 'conflict', 'rephrase', name='argumentrelationtype', native_enum=False)
    argumentrelationtype_enum.create(op.get_bind(), checkfirst=True)

    conflicttype_enum = sa.Enum('rebut', 'undercut', 'incompatibility', name='conflicttype', native_enum=False)
    conflicttype_enum.create(op.get_bind(), checkfirst=True)

    illocutionforce_enum = sa.Enum('assert_', 'deny', 'question', 'define', 'distinguish',
                                   'attribute', 'concede', 'ironic', 'hypothetical',
                                   'prescriptive', name='illocutionforce', native_enum=False)
    illocutionforce_enum.create(op.get_bind(), checkfirst=True)

    transitionhint_enum = sa.Enum('contrast', 'inference', 'concession', 'continuation',
                                  'narrative', name='transitionhint', native_enum=False)
    transitionhint_enum.create(op.get_bind(), checkfirst=True)

    entitytype_enum = sa.Enum('person', 'school', 'position', 'unknown', name='entitytype', native_enum=False)
    entitytype_enum.create(op.get_bind(), checkfirst=True)

    # Argument extraction run tracking table
    op.create_table('argument_extraction_run',
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('pipeline_version', sa.String(length=128), nullable=False),
        sa.Column('git_commit_hash', sa.String(length=64), nullable=True),
        sa.Column('model_name', sa.String(length=128), nullable=False),
        sa.Column('model_fingerprint', sa.String(length=128), nullable=True),
        sa.Column('prompt_name', sa.String(length=128), nullable=False),
        sa.Column('prompt_version', sa.String(length=64), nullable=False),
        sa.Column('params', sa.JSON(), nullable=False, server_default='{}'),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False, server_default='started'),
        sa.Column('error_log', sa.Text(), nullable=True),
        sa.Column('windows_processed', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('propositions_extracted', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('relations_extracted', sa.Integer(), nullable=False, server_default='0'),
        sa.PrimaryKeyConstraint('run_id')
    )

    # L-node: bridges existing Paragraph/SentenceSpan to argument graph
    op.create_table('argument_locution',
        sa.Column('loc_id', sa.UUID(), nullable=False),
        sa.Column('edition_id', sa.UUID(), nullable=False),
        sa.Column('paragraph_id', sa.UUID(), nullable=True),
        sa.Column('sentence_span_id', sa.UUID(), nullable=True),
        sa.Column('text_content', sa.Text(), nullable=False),
        sa.Column('start_char', sa.Integer(), nullable=True),
        sa.Column('end_char', sa.Integer(), nullable=True),
        sa.Column('created_run_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.ForeignKeyConstraint(['edition_id'], ['edition.edition_id'], ),
        sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.para_id'], ),
        sa.ForeignKeyConstraint(['sentence_span_id'], ['sentence_span.span_id'], ),
        sa.PrimaryKeyConstraint('loc_id'),
        sa.CheckConstraint('(paragraph_id IS NOT NULL) OR (sentence_span_id IS NOT NULL)',
                          name='ck_argument_locution_has_text_ref')
    )
    op.create_index('ix_argument_locution_edition', 'argument_locution', ['edition_id'], unique=False)
    op.create_index('ix_argument_locution_paragraph', 'argument_locution', ['paragraph_id'], unique=False)
    op.create_index('ix_argument_locution_sentence_span', 'argument_locution', ['sentence_span_id'], unique=False)

    # I-node: informational content (propositions)
    op.create_table('argument_proposition',
        sa.Column('prop_id', sa.UUID(), nullable=False),
        sa.Column('edition_id', sa.UUID(), nullable=False),
        sa.Column('text_canonical', sa.Text(), nullable=False),
        sa.Column('primary_loc_id', sa.UUID(), nullable=False),
        sa.Column('supporting_loc_ids', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('claim_type', sa.Enum('definition', 'thesis', 'empirical', 'normative',
                                        'methodological', 'objection', 'reply',
                                        name='claimtype', native_enum=False), nullable=True),
        sa.Column('claim_type_raw', sa.Text(), nullable=True),
        sa.Column('polarity', sa.Enum('assert_', 'deny', 'conditional',
                                      name='polarity', native_enum=False), nullable=True),
        sa.Column('polarity_raw', sa.Text(), nullable=True),
        sa.Column('modality', sa.Enum('is_', 'will', 'would', 'can', 'could', 'cannot',
                                      'must', 'should', 'ought', 'may', 'appears_as',
                                      'becomes', 'in_essence_is',
                                      name='modality', native_enum=False), nullable=True),
        sa.Column('modality_raw', sa.Text(), nullable=True),
        sa.Column('dialectical_status', sa.Enum('none', 'tension_pair', 'appearance_essence',
                                                'developmental',
                                                name='dialecticalstatus', native_enum=False),
                                     nullable=True),
        sa.Column('dialectical_status_raw', sa.Text(), nullable=True),
        sa.Column('attributed_to', sa.Text(), nullable=True),
        sa.Column('effective_author_id', sa.UUID(), nullable=True),
        sa.Column('entity_bindings', sa.JSON(), nullable=False, server_default='{}'),
        sa.Column('created_run_id', sa.UUID(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.ForeignKeyConstraint(['edition_id'], ['edition.edition_id'], ),
        sa.ForeignKeyConstraint(['effective_author_id'], ['author.author_id'], ),
        sa.ForeignKeyConstraint(['primary_loc_id'], ['argument_locution.loc_id'], ),
        sa.PrimaryKeyConstraint('prop_id')
    )
    op.create_index('ix_argument_proposition_created_run', 'argument_proposition', ['created_run_id'], unique=False)
    op.create_index('ix_argument_proposition_edition', 'argument_proposition', ['edition_id'], unique=False)

    # L→P edge: illocutionary force
    op.create_table('argument_illocution',
        sa.Column('illoc_id', sa.UUID(), nullable=False),
        sa.Column('source_loc_id', sa.UUID(), nullable=False),
        sa.Column('target_prop_id', sa.UUID(), nullable=False),
        sa.Column('force', illocutionforce_enum, nullable=False),
        sa.Column('attributed_to', sa.Text(), nullable=True),
        sa.Column('is_implicit_opponent', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_run_id', sa.UUID(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.ForeignKeyConstraint(['source_loc_id'], ['argument_locution.loc_id'], ),
        sa.ForeignKeyConstraint(['target_prop_id'], ['argument_proposition.prop_id'], ),
        sa.PrimaryKeyConstraint('illoc_id')
    )
    op.create_index('ix_argument_illocution_source', 'argument_illocution', ['source_loc_id'], unique=False)
    op.create_index('ix_argument_illocution_target', 'argument_illocution', ['target_prop_id'], unique=False)

    # S-node: argumentative relations
    op.create_table('argument_relation',
        sa.Column('rel_id', sa.UUID(), nullable=False),
        sa.Column('edition_id', sa.UUID(), nullable=False),
        sa.Column('source_prop_id', sa.UUID(), nullable=False),
        sa.Column('target_prop_id', sa.UUID(), nullable=False),
        sa.Column('relation_type', argumentrelationtype_enum, nullable=False),
        sa.Column('conflict_type', conflicttype_enum, nullable=True),
        sa.Column('evidence_loc_ids', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('justification', sa.Text(), nullable=True),
        sa.Column('created_run_id', sa.UUID(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.ForeignKeyConstraint(['edition_id'], ['edition.edition_id'], ),
        sa.ForeignKeyConstraint(['source_prop_id'], ['argument_proposition.prop_id'], ),
        sa.ForeignKeyConstraint(['target_prop_id'], ['argument_proposition.prop_id'], ),
        sa.PrimaryKeyConstraint('rel_id')
    )
    op.create_index('ix_argument_relation_edition', 'argument_relation', ['edition_id'], unique=False)
    op.create_index('ix_argument_relation_source', 'argument_relation', ['source_prop_id'], unique=False)
    op.create_index('ix_argument_relation_target', 'argument_relation', ['target_prop_id'], unique=False)

    # Discourse transition markers
    op.create_table('argument_transition',
        sa.Column('transition_id', sa.UUID(), nullable=False),
        sa.Column('edition_id', sa.UUID(), nullable=False),
        sa.Column('from_loc_id', sa.UUID(), nullable=True),
        sa.Column('to_loc_id', sa.UUID(), nullable=True),
        sa.Column('hint_type', transitionhint_enum, nullable=False),
        sa.Column('marker_text', sa.String(length=256), nullable=False),
        sa.Column('paragraph_id', sa.UUID(), nullable=True),
        sa.Column('sentence_span_id', sa.UUID(), nullable=True),
        sa.Column('created_run_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.ForeignKeyConstraint(['edition_id'], ['edition.edition_id'], ),
        sa.ForeignKeyConstraint(['from_loc_id'], ['argument_locution.loc_id'], ),
        sa.ForeignKeyConstraint(['to_loc_id'], ['argument_locution.loc_id'], ),
        sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.para_id'], ),
        sa.ForeignKeyConstraint(['sentence_span_id'], ['sentence_span.span_id'], ),
        sa.PrimaryKeyConstraint('transition_id')
    )
    op.create_index('ix_argument_transition_edition', 'argument_transition', ['edition_id'], unique=False)
    op.create_index('ix_argument_transition_from', 'argument_transition', ['from_loc_id'], unique=False)
    op.create_index('ix_argument_transition_to', 'argument_transition', ['to_loc_id'], unique=False)

    # Entity catalog for normalization
    op.create_table('entity_catalog',
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('entity_type', entitytype_enum, nullable=False),
        sa.Column('label_canonical', sa.String(length=512), nullable=False),
        sa.Column('aliases', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('entity_metadata', sa.JSON(), nullable=True),
        sa.Column('author_id', sa.UUID(), nullable=True),
        sa.Column('created_run_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False, server_default='proposed'),
        sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_entity_catalog_label', 'entity_catalog', ['label_canonical'], unique=False)
    op.create_index('ix_entity_catalog_type', 'entity_catalog', ['entity_type'], unique=False)

    # Entity bindings (surface form to canonical entity)
    op.create_table('entity_binding',
        sa.Column('binding_id', sa.UUID(), nullable=False),
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('surface_form', sa.String(length=512), nullable=False),
        sa.Column('proposition_id', sa.UUID(), nullable=True),
        sa.Column('locution_id', sa.UUID(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('created_run_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['created_run_id'], ['argument_extraction_run.run_id'], ),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_catalog.entity_id'], ),
        sa.ForeignKeyConstraint(['locution_id'], ['argument_locution.loc_id'], ),
        sa.ForeignKeyConstraint(['proposition_id'], ['argument_proposition.prop_id'], ),
        sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_index('ix_entity_binding_entity', 'entity_binding', ['entity_id'], unique=False)
    op.create_index('ix_entity_binding_surface', 'entity_binding', ['surface_form'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_binding_surface', table_name='entity_binding')
    op.drop_index('ix_entity_binding_entity', table_name='entity_binding')
    op.drop_table('entity_binding')

    op.drop_index('ix_entity_catalog_type', table_name='entity_catalog')
    op.drop_index('ix_entity_catalog_label', table_name='entity_catalog')
    op.drop_table('entity_catalog')

    op.drop_index('ix_argument_transition_to', table_name='argument_transition')
    op.drop_index('ix_argument_transition_from', table_name='argument_transition')
    op.drop_index('ix_argument_transition_edition', table_name='argument_transition')
    op.drop_table('argument_transition')

    op.drop_index('ix_argument_relation_target', table_name='argument_relation')
    op.drop_index('ix_argument_relation_source', table_name='argument_relation')
    op.drop_index('ix_argument_relation_edition', table_name='argument_relation')
    op.drop_table('argument_relation')

    op.drop_index('ix_argument_illocution_target', table_name='argument_illocution')
    op.drop_index('ix_argument_illocution_source', table_name='argument_illocution')
    op.drop_table('argument_illocution')

    op.drop_index('ix_argument_proposition_created_run', table_name='argument_proposition')
    op.drop_index('ix_argument_proposition_edition', table_name='argument_proposition')
    op.drop_table('argument_proposition')

    op.drop_index('ix_argument_locution_sentence_span', table_name='argument_locution')
    op.drop_index('ix_argument_locution_paragraph', table_name='argument_locution')
    op.drop_index('ix_argument_locution_edition', table_name='argument_locution')
    op.drop_table('argument_locution')

    op.drop_table('argument_extraction_run')

    # Drop enum types
    sa.Enum(name='entitytype', native_enum=False).drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transitionhint', native_enum=False).drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='illocutionforce', native_enum=False).drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='conflicttype', native_enum=False).drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='argumentrelationtype', native_enum=False).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
